coffeecard/CoffeeCard.Common/Configuration/IdentitySettings.cs, coffeecard/CoffeeCard.Common/Configuration/LoginLimiterSettings.cs, coffeecard/CoffeeCard.Tests.Unit/Services/AccountServiceTest.cs, coffeecard/CoffeeCard.Tests.Unit/Services/LoginLimiterTests.cs, coffeecard/CoffeeCard.WebApi/CoffeeCard.WebApi.csproj, coffeecard/CoffeeCard.WebApi/Services/AccountService.cs, coffeecard/CoffeeCard.WebApi/Services/ILoginLimiter.cs, coffeecard/CoffeeCard.WebApi/Services/LeaderboardService.cs, coffeecard/CoffeeCard.WebApi/Services/LoginLimiter.cs, coffeecard/CoffeeCard.WebApi/Services/PurchaseService.cs, coffeecard/CoffeeCard.WebApi/Services/TicketService.cs, coffeecard/CoffeeCard.WebApi/Startup.cs, coffeecard/CoffeeCard.WebApi/appsettings-for-tests.json
As discussed earlier, here is a solution using a dictionary(map) in order to solve our potential issue
=> Implementation of login timeout that should be able to help alleviate potential problems with the login endpoint

coffeecard/CoffeeCard.WebApi/Controllers/AccountController.cs, coffeecard/CoffeeCard.WebApi/Services/AccountService.cs, coffeecard/CoffeeCard.WebApi/Services/IAccountService.cs
Added a check, so an authenticated user may only request their own information
=> Users may only retrieve their own info

coffeecard/CoffeeCard.Models/DataTransferObjects/User/LoginDTO.cs, coffeecard/CoffeeCard.WebApi/Startup.cs
=> Minor documentation fix

coffeecard/CoffeeCard.Models/DataTransferObjects/User/LoginDTO.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/User/RegisterDTO.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/User/UpdateUserDTO.cs
=> Minor doc updates

coffeecard/CoffeeCard.Models/DataTransferObjects/v2/MobilePay/MobilePayWebhook.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/InitatePurchaseRequest.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/InitiatePurchaseResponse.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/MobilePayPaymentDetails.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/PaymentDetails.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/PaymentType.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/Purchase.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/PurchaseStatus.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/MobilePayController.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/Purchasesontroller.cs, coffeecard/CoffeeCard.WebApi/Startup.cs
=> Initial API design and models for Purchases and MobilePay

coffeecard/CoffeeCard.Models/DataTransferObjects/v2/AppConfig/AppConfig.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/AppConfigController.cs
=> AppConfig Controller v2

coffeecard/CoffeeCard.Library/CoffeeCard.Library.csproj, coffeecard/CoffeeCard.Library/Migrations/20220205202109_initial-postgres.Designer.cs, coffeecard/CoffeeCard.Library/Migrations/20220205202109_initial-postgres.cs, coffeecard/CoffeeCard.Library/Migrations/CoffeeCardContextModelSnapshot.cs, coffeecard/CoffeeCard.Tests.Integration/CoffeeCard.Tests.Integration.csproj, coffeecard/CoffeeCard.Tests.Unit/CoffeeCard.Tests.Unit.csproj, coffeecard/CoffeeCard.WebApi/CoffeeCard.WebApi.csproj, coffeecard/CoffeeCard.WebApi/Startup.cs, coffeecard/CoffeeCard.WebApi/appsettings.json, coffeecard/docker-compose.yml
We move to Postgres DB when moving to Digital Ocean
- EF versions bumped
- Use Postgres SQL driver
- Update migrations
=> Use Postgres

coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs
=> compare usergroup to product usergroups

coffeecard/CoffeeCard.Library/Services/LeaderboardService.cs
Closes #80 
Refactored GetLeaderboard to make it more readable, and fixed an error where the user is not anonymized
=> Anonymized user are actually anonymized

coffeecard/.gitignore, coffeecard/CoffeeCard.Common/Errors/ConflictException.cs, coffeecard/CoffeeCard.Library/Migrations/20221206185427_AddDescriptionAndRequesterToVoucher.Designer.cs, coffeecard/CoffeeCard.Library/Migrations/20221206185427_AddDescriptionAndRequesterToVoucher.cs, coffeecard/CoffeeCard.Library/Migrations/20221220181445_ChangeTypeOfRequesterToString.Designer.cs, coffeecard/CoffeeCard.Library/Migrations/20221220181445_ChangeTypeOfRequesterToString.cs, coffeecard/CoffeeCard.Library/Services/AccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/IPurchaseService.cs, coffeecard/CoffeeCard.Library/Services/v2/IVoucherService.cs, coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs, coffeecard/CoffeeCard.Library/Services/v2/VoucherService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Voucher/IssueVoucherRequest.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Voucher/IssueVoucherResponse.cs, coffeecard/CoffeeCard.Models/Entities/Voucher.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/VoucherServiceTests.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/VouchersController.cs, coffeecard/CoffeeCard.WebApi/Helpers/ApiExceptionFilter.cs, coffeecard/CoffeeCard.WebApi/Startup.cs
=> Issue vouchers endpoint

coffeecard/CoffeeCard.Models/DataTransferObjects/User/UserDTO.cs, coffeecard/CoffeeCard.WebApi/Controllers/AccountController.cs, coffeecard/CoffeeCard.WebApi/appsettings.json
=> add user role to AccountController Get

coffeecard/CoffeeCard.Common/Configuration/MobilePaySettingsV2.cs, coffeecard/CoffeeCard.MobilePay/Service/v2/MobilePayPaymentsService.cs, coffeecard/CoffeeCard.WebApi/appsettings.json, infrastructure/dev.settings.json, infrastructure/prd.settings.json
The AnalogAppRedirectUri is different depending on which environment the server is in
Closes #177
=> feat: Add AnalogAppRedirectUri to MobilePaySettingsV2

coffeecard/CoffeeCard.Library/Services/v2/AccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/IAccountService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/ResendAccountVerificationEmailRequest.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/AccountServiceTest.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
=> Resend verification email endpoint 

coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs
=> Fix RedeemVoucher check on voucher usage

coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
* Change route to use api version
=> Use api version as part of route in accontAController v2 (#198)

coffeecard/CoffeeCard.Library/Services/v2/IProductService.cs, coffeecard/CoffeeCard.Library/Services/v2/ProductService.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/ProductsController.cs
Refactored product retrieval by removing the public listing feature and enforcing authentication. Any unauthenticated access will now result in a 401 Unauthorized response.
Resolves #239, unblocks https://github.com/AnalogIO/coffeecard_app/issues/564
=> Removed public product listing endpoint

coffeecard/CoffeeCard.WebApi/Controllers/v2/ProductsController.cs
Required for the app to know what menu items can be claimed with a ticket (if the ticket is for a product that is no longer for sale)
=> Adds V2 GET products/[id] endpoint

coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/FreeProductPaymentDetails.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/MobilePayPaymentDetails.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/PaymentDetails.cs
- Caused a breaking change in consuming app by accident
=> Reintroduced discriminator on inherited responses

coffeecard/CoffeeCard.MobilePay/Service/v2/IMobilePayPaymentsService.cs, coffeecard/CoffeeCard.MobilePay/Service/v2/MobilePayPaymentsService.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/HealthController.cs
Webhooks Api is deprected in the new Vipps MobilePay integration. Rely on the PaymentsApi instead
=> Change MobilePay health check query

coffeecard/CoffeeCard.Library/Services/v2/IPurchaseService.cs, coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs, coffeecard/CoffeeCard.MobilePay/Service/v2/IMobilePayPaymentsService.cs, coffeecard/CoffeeCard.MobilePay/Service/v2/MobilePayPaymentsService.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/PurchaseServiceTests.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/PurchasesController.cs
This hasn't been tested, as it is currently impossible
See https://developer.mobilepay.dk/docs/app-payments/transition-to-one-platform#test
=> RefundPayment on PurchasesController

coffeecard/CoffeeCard.Tests.Unit/Services/v2/AccountServiceTest.cs
Fixes flakiness by ensuring the users have the same privacy setting
=> Fixes flaky test in account service
