coffeecard/CoffeeCard.Tests.Integration/CoffeeCard.Tests.Integration.csproj, coffeecard/CoffeeCard.Tests.Integration/WebApplication/CustomWebApplicationFactory.cs, coffeecard/CoffeeCard.Tests.Unit/Helpers/MobilePayApiHttpClientTests.cs, coffeecard/CoffeeCard.Tests.Unit/Services/MobilePayServiceTest.cs, coffeecard/CoffeeCard/CoffeeCard.csproj, coffeecard/CoffeeCard/Configuration/DatabaseSettings.cs, coffeecard/CoffeeCard/Configuration/EnvironmentSettings.cs, coffeecard/CoffeeCard/Configuration/IdentitySettings.cs, coffeecard/CoffeeCard/Configuration/MailgunSettings.cs, coffeecard/CoffeeCard/Configuration/MobilePaySettings.cs, coffeecard/CoffeeCard/Controllers/PurchasesController.cs, coffeecard/CoffeeCard/Helpers/MobilePay/MobilePayApiHttpClient.cs, coffeecard/CoffeeCard/Migrations/20191012125617_Initial - test.Designer.cs, coffeecard/CoffeeCard/Migrations/CoffeecardContextModelSnapshot.cs, coffeecard/CoffeeCard/Models/CoffeecardContext.cs, coffeecard/CoffeeCard/Models/DataTransferObjects/AppConfig/AppConfigDTO.cs, coffeecard/CoffeeCard/Program.cs, coffeecard/CoffeeCard/Services/AccountService.cs, coffeecard/CoffeeCard/Services/AppConfigService.cs, coffeecard/CoffeeCard/Services/EmailService.cs, coffeecard/CoffeeCard/Services/LeaderboardService.cs, coffeecard/CoffeeCard/Services/MobilePayService.cs, coffeecard/CoffeeCard/Services/ProductService.cs, coffeecard/CoffeeCard/Services/ProgrammeService.cs, coffeecard/CoffeeCard/Services/PurchaseService.cs, coffeecard/CoffeeCard/Services/TicketService.cs, coffeecard/CoffeeCard/Services/TokenService.cs, coffeecard/CoffeeCard/Startup.cs, coffeecard/CoffeeCard/appsettings-for-tests.json
- AppSettings are parsed to specialized settings objects instead of reading configuration from strings
- If a settings is `null` at startup, the project will throw an Exception
=> Strongly typed app settings

coffeecard/CoffeeCard.Tests.Unit/Models/SemesterStartTests.cs, coffeecard/CoffeeCard.WebApi/Models/Statistic.cs
Fix a bug that would attempt to return a DateTime with day > 31
Add guard clause for autumn semester case
=> Fix GetSemesterStart

coffeecard/CoffeeCard.Common/Configuration/LoginLimiterSettings.cs, coffeecard/CoffeeCard.Library/Services/AccountService.cs, coffeecard/CoffeeCard.Library/Services/LoginLimiter.cs, coffeecard/CoffeeCard.Tests.Unit/Services/AccountServiceTest.cs, coffeecard/CoffeeCard.Tests.Unit/Services/LoginLimiterTests.cs, coffeecard/CoffeeCard.WebApi/appsettings.json
The reason for this Pr is to increase the speed that our unit tests can complete at. This removes an artificial limit on them, where they could only complete after a minute had passed.
Do note, the appsettings.json used for production needs to be updated with the new value instead before deployment
=> Refactored the loginLimiter to receive the logout time in seconds

coffeecard/CoffeeCard.Library/Services/v2/PurchaseService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Purchase/SimplePurchaseResponse.cs
Reason for adding: This helps the app when it needs to retrieve receipts, since it can get all required information in one request, instead of having to request the product names separately.
=> Added productName as a property to SimplePurchaseResponse

coffeecard/CoffeeCard.Library/Services/AccountService.cs, coffeecard/CoffeeCard.Library/Services/IAccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/AccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/IAccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/ILeaderboardService.cs, coffeecard/CoffeeCard.Library/Services/v2/LeaderboardService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Programme/ProgrammeDto.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/RegisterAccountRequest.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/UpdateUserRequest.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/UserResponse.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/AccountServiceTest.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs, coffeecard/CoffeeCard.WebApi/Pages/VerifyDelete.cshtml.cs, coffeecard/CoffeeCard.WebApi/Startup.cs
- Refactored the service layer, so account controller v2 no longer relies on the v1 account service. 
- Added get and update to account controller v2. The new functionality is it now includes all information about a user's programme, not only the ID of it.
- Removed methods from account service v1 that supported functionality in account controller v2
-  Added tests for all methods in AccountService v2
=> Implemented get and update endpoints for AccountController v2 

coffeecard/CoffeeCard.WebApi/Controllers/TicketsController.cs
Change Use Ticket API endpoint to use TicketService considering free products
=> Change Use Ticket API endpoint

coffeecard/CoffeeCard.WebApi/Controllers/AccountController.cs
Fixes a typo in the forgotten password response
=> Anti 🤠 -measures

coffeecard/CoffeeCard.Library/Services/v2/AccountService.cs
According to [this article from the EF Core docs](https://learn.microsoft.com/en-us/ef/core/miscellaneous/collations-and-case-sensitivity#translation-of-built-in-net-string-operations), using the `StringComparison` enum in `Equals` does not correctly translate to SQL, and as such EF Core will throw an exception. 
This pull request changes the `Where` clause to simply perform `.ToLower()` on each string, to ensure case-insensitivity
=> fix: Correct where clause in resend verification

coffeecard/CoffeeCard.WebApi/Controllers/v2/ProductsController.cs
The MapProductToDto in the productscontroller was missing one line that converts the user groups on a product to usergroups on a ProductResponse.
This allows a frontend to actually see the usergroups on a product.
=> Expose usergroups on getproducts

coffeecard/CoffeeCard.Library/Services/v2/IProductService.cs, coffeecard/CoffeeCard.Library/Services/v2/ProductService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/Products/ProductResponse.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/ProductServiceTest.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/ProductsController.cs
Some weird merge conflicts arised on #232 after #234 was made. Probably due to me branching out from the wrong branch initially. Here is a new pull request instead :)
This adds an endpoint for the product management with frontend in https://github.com/AnalogIO/shifty-webapp/pull/20 and discussed as endpoint in #217 (and slack).
The API will have the endpoint /api/v2/products/all which gives all products, not restricted to a specific usergroup or restricted to only visible products.
This endpoint is only accessible for users with Board privileges and will allow board members to manage the visibilty of products or products that they otherwise don't have access to themselves in the app.
=> Adds GET products/all for privileged users

coffeecard/CoffeeCard.WebApi/Controllers/v2/AccountController.cs
See below screenshot showing that the service returns a `UserSearchResponse` and not an enumerable.
This affects Shifty when we use the GenerateApi tool and the generated code expects to return a list.
A `UserSearchResponse` contains an enumerable of SimpleUserResponse and a TotalUsers (count) property.
=> Search returns single element that contains list

coffeecard/CoffeeCard.Library/CoffeeCard.Library.csproj, coffeecard/CoffeeCard.Library/Migrations/20240227174524_AddUserGroupIndexToUsers.Designer.cs, coffeecard/CoffeeCard.Library/Migrations/20240227174524_AddUserGroupIndexToUsers.cs, coffeecard/CoffeeCard.Library/Services/v2/AccountService.cs, coffeecard/CoffeeCard.Library/Services/v2/IAccountService.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/AccountUserGroup.cs, coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/WebhookUpdateUserGroupRequest.cs, coffeecard/CoffeeCard.Models/Entities/AccountUserGroup.cs, coffeecard/CoffeeCard.Models/Entities/User.cs, coffeecard/CoffeeCard.Tests.Unit/Services/v2/AccountServiceTest.cs, coffeecard/CoffeeCard.WebApi/CoffeeCard.WebApi.csproj, coffeecard/CoffeeCard.WebApi/Controllers/v2/WebhooksController.cs
Implements the endpoint `PUT /api/v2/webhooks/accounts/user-group`,
allowing an external service to update user groups in bulk.
Example request body:
```
{
"privilegedUsers": [
{ "accountId": 123, "userGroup": "Manager" },
{ "accountId": 124, "userGroup": "Barista" }
]
}
```
The X-Api-Key header should be present on the request with a valid API
key.
The userGroup should be one of:
- Barista
- Manager
- Board
- (Customer will also work, but will have the same effect as not
specifying the user in the request)
I have been unable to implement an integration test, since
EFCore.InMemory does not seem to support the performance-optimized
ExecuteUpdate that is implemented in EF Core 7 and used in this service.
Reference:
https://stackoverflow.com/questions/74907256/ef-7-new-executedelete-and-execu …
=> Webhook for bulk updating accounts usergroup

coffeecard/CoffeeCard.Models/DataTransferObjects/v2/User/UserSearchResponse.cs
With the new Json serializer from #266, fields are no longer serialized.
Preferably, we would have added the Json options `options.JsonSerializerOptions.IncludeFields = true;` to ensure that no other functionality broke. However, due to an issue raised [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2423), the schema in Swagger will not show fields despite setting this option. Thus, our API-generation would not work for e.g. Shifty that uses this.
Instead, I have looked through `CoffeeCard.Models` and not found other examples where we are using fields and not properties.
=> Changes Users to property

coffeecard/CoffeeCard.Library/CoffeeCard.Library.csproj, coffeecard/CoffeeCard.Library/Services/v2/WebhookService.cs, coffeecard/CoffeeCard.Library/Utils/FeatureFlags.cs, coffeecard/CoffeeCard.WebApi/CoffeeCard.WebApi.csproj, coffeecard/CoffeeCard.WebApi/Program.cs, coffeecard/CoffeeCard.WebApi/Startup.cs, coffeecard/CoffeeCard.WebApi/appsettings.json
When migrating to the new MobilePay Vipps API, the existing MobilePay Webhooks API will be disabled, thus we need a way to disable the feature until the new integration has been developed. We use Feature Flags to disable registration to the Webhooks API.
=> Introduce Feature Flag to control MobilePay Webhooks registration

coffeecard/CoffeeCard.WebApi/Controllers/v2/ProductsController.cs, coffeecard/CoffeeCard.WebApi/Controllers/v2/VouchersController.cs
Users with role Manager can now (alongside users with role Board) issue vouchers, which also includes access to the products/all endpoint. 
This is required to list products available to issue products on. (This endpoint is used for issuing vouchers as well as the product manager but nowhere else. The endpoint for products that is usable per user group used by the app is a different endpoint)
=> Adds manager access to issue vouchers

coffeecard/CoffeeCard.WebApi/Controllers/v2/AdminStatisticsController.cs
Currently, auto-generated swagger documentation shows only a single response item in the example response value, when the actual result is a JSON array (one element per product type for the given period).
This fix will prevent issues for developers in shifty when generating the API interface.
=> Changes unused clips response type to enumerable

coffeecard/CoffeeCard.Common/Configuration/SmtpSettings.cs, coffeecard/CoffeeCard.Library/Services/EmailService.cs, coffeecard/CoffeeCard.Library/Services/IEmailSender.cs, coffeecard/CoffeeCard.Library/Services/MailgunEmailSender.cs, coffeecard/CoffeeCard.Library/Services/SmtpEmailSender.cs, coffeecard/CoffeeCard.WebApi/Helpers/ConfigurationServiceCollectionExtension.cs, coffeecard/CoffeeCard.WebApi/Startup.cs, coffeecard/CoffeeCard.WebApi/appsettings.json, coffeecard/docker-compose.yml
This PR adds an `IEmailSender` abstraction along with implementations `SmtpEmailSender` and `MailgunEmailSender`, and refactors `EmailService` to use said abstraction. The main idea is to allow for local email testing using an SMTP server such as [MailHog](https://github.com/mailhog/MailHog), which has also been added to the Docker Compose configuration.
=> Add EmailSender abstraction for sending mails using either SMTP or Mailgun

.github/workflows/sonarcloud.yml
Updates the SonarCloud workflow to some newer versions (mostly taken from the template given by SonarCloud themselves), and hopefully fixes the coverage issue in #298 by fixing the path by changing .net6 -> .net8
=> Update SonarCloud workflow, fix .net8 path

coffeecard/CoffeeCard.WebApi/Program.cs, coffeecard/CoffeeCard.WebApi/Startup.cs
- The grafana collector for otel is caps sensitive, so does not map the Service.Name to service_name field. Now corrected
- Reversed the order of registration for AddService and AddAzureAppServiceDetector, so we overrite the detector, and not the other way around
=> Minor fixes for otel serivce name

coffeecard/CoffeeCard.WebApi/Controllers/v2/MobilePayController.cs
Changes logging to use json serilization instead of standard toString method for logging the incoming request
=> Add proper logging of request object for webhook endpoint
